name: Check Published

on:
  schedule:
    - cron: '11 23 * * *'

jobs:
  checkPublished:
    name: Check Published
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Check Published
        uses: checkdigit/github-actions/check-published@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN_PUBLISH }}
          DEBUG: '*'
          SLACK_PUBLISH_MISMATCH: ${{ secrets.SLACK_PUBLISH_MISMATCH }}
