name: Check Pull Request Reviews

on:
  pull_request_review:
    types: [submitted]

jobs:
  checkPrReviews:
    runs-on: ubuntu-latest
    name: Check PR Reviews
    steps:
      - name: Perform Check of PR Reviews
        uses: checkdigit/github-actions/check-pr-reviews@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
