name: Coverage

on:
  pull_request:
    branches:
      - 'main'

env:
  CI: true

jobs:
  coverage:
    runs-on: ubuntu-latest
    name: Coverage
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Calculate Code Coverage
        run: npm run ci:coverage
      - name: Create Coverage Report for base branch
        run: |
          mv coverage/lcov.info coverage/lcov_head.info
          git fetch
          git checkout origin/${{ github.event.pull_request.base.ref }}
          npm ci --ignore-scripts && npm run ci:coverage
      - name: Post Coverage Report
        uses: checkdigit/github-actions/coverage-reporter@main
        with:
          lcov-file: 'coverage/lcov_head.info'
          lcov-base: 'coverage/lcov.info'
          delete-old-comments: true
