name: Publish Beta Package

on:
  pull_request:
    branches:
      - 'main'

jobs:
  publishBeta:
    runs-on: ubuntu-latest
    name: Publish Beta
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Check Label
        uses: checkdigit/github-actions/check-label@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Audit Signatures
        run: npm audit signatures
      - name: Run Test
        run: npm run test
      - name: Prepare Beta
        id: prepare-beta
        uses: checkdigit/github-actions/prepare-beta@main
      - name: Publish Beta
        run: npm publish --tag beta
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN_PUBLISH }}
      - name: Comment
        uses: checkdigit/github-actions/comment-npm-publish@main
        with:
          betaPackage: ${{ steps.prepare-beta.outputs.betaPackage }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
